name: Mine Films
favicon: null
layout_spectrum: 1
typography_spectrum: 0.39649
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#110c10'
    - '#3c9498'
    - '#17424b'
    - '#b8d6d4'
    - '#93704f'
  brandStrength: 0.0701847979798913
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
